compilers:
  - compiler:
      spec: oneapi@2023.05.15
      paths:
        cc: /soft/restricted/CNDA/updates/2023.05.15.001/oneapi/compiler/eng-20230512/compiler/linux/bin/icx
        cxx: /soft/restricted/CNDA/updates/2023.05.15.001/oneapi/compiler/eng-20230512/compiler/linux/bin/icpx
        f77: /soft/restricted/CNDA/updates/2023.05.15.001/oneapi/compiler/eng-20230512/compiler/linux/bin/ifx
        fc: /soft/restricted/CNDA/updates/2023.05.15.001/oneapi/compiler/eng-20230512/compiler/linux/bin/ifx
      flags: {}
      operating_system: sles15
      target: any
      modules: 
        - oneapi/eng-compiler/2023.05.15.006
        - mpich/51.2/icc-all-pmix-gpu
        - libfabric
        - intel_compute_runtime/release/agama-devel-647
      environment:
        set:
          DPLROOT: /lus/gila/projects/CSC249ADSE13_CNDA/jrood/exawind/oneDPL
      extra_rpaths: []
