packages:
  mpich:
    require: "@51.2"
    buildable: false
    externals:
      - spec: "mpich@51.2"
        prefix: /soft/restricted/CNDA/updates/mpich/51.2/mpich-ofi-all-icc-default-pmix-gpu-drop51
        modules:
          - mpich/51.2/icc-all-pmix-gpu
          - cray-libpals
          - cray-pals
  nalu-wind:
    require: "~trilinos-solvers"
  amr-wind:
    variants: +tiny_profile build_type=Release
  trilinos:
    require: "+tpetra+kokkos"
  boost:
    version: [1.78.0]
    variants: ~shared+pic
  all:
    compiler: [oneapi]
    variants: build_type=Release
    providers:
      mpi: [mpich]
      blas: [openblas]
      lapack: [openblas]
