compilers:
  - compiler:
      spec: clang@15.0.0
      paths:
        cc: cc
        cxx: CC
        f77: /opt/cray/pe/gcc/12.2.0/bin/gfortran
        fc: /opt/cray/pe/gcc/12.2.0/bin/gfortran
      operating_system: sles15
      target: any
      modules:
       - PrgEnv-gnu-amd/8.4.0
       - PrgEnv-gnu/8.3.3
       - gcc/12.2.0
       - craype-x86-trento
       - cray-libsci/22.12.1.1
       - libfabric/1.15.2.0
       - craype-network-ofi
       - cray-python/3.9.13.1
       - DefApps/default
       - amd-mixed/5.4.3
       - craype/2.7.19
       - cray-dsmml/0.2.2
       - cray-pmi/6.1.8
       - cray-mpich/8.1.23
      extra_rpaths: []
      environment:
        prepend_path:
          PKG_CONFIG_PATH: /opt/cray/xpmem/2.6.2-2.5_2.22__gd067c3f.shasta/lib64/pkgconfig:/sw/frontier/spack-envs/base/opt/linux-sles15-x86_64/gcc-7.5.0/zlib-1.2.11-zuyclcfig4tizmb2bm2h4roqsp3rwn2y/lib/pkgconfig
