compilers:
  - compiler:
      spec: clang@15.0.0
      paths:
        cc: cc
        cxx: CC
        f77: ftn
        fc: ftn
      flags: {}
      operating_system: sles15
      target: any
      modules:
        - PrgEnv-cray-amd/8.4.0
        - PrgEnv-cray/8.3.3
        - libfabric/1.15.2.0
        - cce/15.0.0
        - DefApps/default
        - cray-dsmml/0.2.2
        - craype-network-ofi
        - amd-mixed/5.4.3
        - cray-mpich/8.1.23
        - craype-x86-trento
        - craype/2.7.19
        - cray-libsci/22.12.1.1
      extra_rpaths: []
      environment:
        prepend_path:
          PKG_CONFIG_PATH: /opt/cray/xpmem/2.6.2-2.5_2.22__gd067c3f.shasta/lib64/pkgconfig:/sw/frontier/spack-envs/base/opt/linux-sles15-x86_64/gcc-7.5.0/zlib-1.2.11-zuyclcfig4tizmb2bm2h4roqsp3rwn2y/lib/pkgconfig
