packages:
  mpich:
    require: "@51.2"
    buildable: false
    externals:
      - spec: "mpich@51.2"
        prefix: /opt/aurora/23.073.0/CNDA/mpich/51.2/mpich-ofi-all-icc-default-pmix-gpu-drop51
        modules:
          - mpich/51.2/icc-all-pmix-gpu 
  nalu-wind:
    require: "~trilinos-solvers"
  amr-wind:
    variants: +tiny_profile build_type=Release
  trilinos:
    require: "+tpetra+kokkos"
  boost:
    version: [1.78.0]
    variants: ~shared+pic
  openssl:
    require: "@1.1.1u"
    buildable: false
    externals:
      - spec: "openssl@1.1.1u"
        prefix: /usr
  all:
    compiler: [oneapi]
    variants: build_type=Release
    providers:
      mpi: [mpich]
      blas: [openblas]
      lapack: [openblas]
